# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46bb3da9faed7317229a2762f588887e9540824f2bbb60140f54f16c063720d65d6ea02710db07c32737b7d15c48b1ae1d42fb225d31ea6489fa8ea0453333eb

test:
  secret_key_base: b12871c7a7bb89e1a206694e1277933f9ecd52080ad289dd6b3b015b11228f93081fa80edf59a5c008f714d3032676cee66634e2a725c33816630280f208c243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
